### ISSUE TITLE
Error when using for multiple text nodes (when selector points at a collection of nodes)

### ISSUE THREAD

**Issue by aderchox** [yowainwright/shave#242]
## What Is the issue?
This is the error:
> Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at shave (shave.es.js:109:16)
    at NotificationItem.tsx:51:5
    at commitHookEffectListMount (react-dom.development.js:23049:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24816:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24781:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24768:7)
    at commitPassiveMountEffects (react-dom.development.js:24756:3)
    at flushPassiveEffectsImpl (react-dom.development.js:26990:3)
    at flushPassiveEffects (react-dom.development.js:26935:14)
    at commitRootImpl (react-dom.development.js:26886:5)

followed by more similar errors, but I think the gist of it is, shave expects the selector to point to only a single node on the page, while in many real-world practical cases, this might not be the case.

## Provide issue context below using code examples, images, or links

Here's a codesandbox I've made to reproduce this bug: [codesandbox](https://codesandbox.io/s/ellipsis-with-shave-1bo5g6?file=/src/App.js)
First click on the top Toggle button and then while it's still open, click on the below Toggle button.

**Comment by yowainwright** [comment]
This issue is **valid**—and deeply related to #248 ! 🎉
